[pytest]
markers =
    valid: mark a test as valid scenario
    negative: mark a test as negative scenario
    smoke: mark a test as smoke scenario
    regression: mark a test as regression scenario
    performance: mark a test as performance scenario
    invalid: mark a test as invalid scenario
    positive: mark a test as positive scenario
    health: mark a test as health scenario
    exception: mark a test as exception scenario
    unit: mark a test as unit scenario
