[pytest]
markers =
    valid: mark a test as valid scenario
    negative: mark a test as negative scenario
    functional: mark a test as functional scenario
    performance: mark a test as performance scenario
    invalid: mark a test as invalid scenario
    smoke: mark a test as smoke scenario
    regression: mark a test as regression scenario
    security: mark a test as security scenario
    positive: mark a test as positive scenario
    unit: mark a test as unit scenario
